#!/bin/bash
# fleet-report.sh [email] — full fleet status report (runs ON the Pi; cron 7:00/19:00 local).
# Prints to stdout; with "email" arg also mails it to the owner.
set -u
source "$(dirname "$0")/checks.lib.sh"

FAILS=$(failed_services); HOSTI=$(host_issues)
VERDICT="OK"; [ -n "$FAILS$HOSTI" ] && VERDICT="DEGRADED"

prom() { curl -s -m 8 "http://localhost:9090/api/v1/query" --data-urlencode "query=$1" \
  | python3 -c "import sys,json
try:
    for r in json.load(sys.stdin)['data']['result']:
        lbl=r['metric'].get('instance') or r['metric'].get('job','')
        print(f\"  {lbl}: {r['value'][1]}\")
except Exception: print('  (query failed)')"; }

REPORT=$(
echo "pi-fleet status — $(date '+%F %T %Z') — verdict: $VERDICT"
echo "======================================================================"
[ -n "$FAILS" ] && { echo; echo "!! FAILING NOW:"; echo "$FAILS" | sed 's/|/ — /;s/^/  /'; }
[ -n "$HOSTI" ] && { echo; echo "!! HOST ISSUES:"; echo "$HOSTI" | sed 's/|/ — /;s/^/  /'; }

echo; echo "## Host (pi-node1)"
echo "  $(uptime | sed 's/^ *//')"
echo "  temp: $(host_temp)C | disk free: $(df -h / | awk 'NR==2{print $4" ("$5" used)"}') | mem free: $(free -h | awk '/Mem:/{print $7}')"

echo; echo "## Services ($(running_services | wc -l)/$(expected_services | wc -l) running)"
$COMPOSE ps --format 'table {{.Name}}\t{{.Status}}' 2>/dev/null | sed 's/^/  /'

echo; echo "## Application HTTP checks"
while IFS='|' read -r name url svc; do
    [ -z "$name" ] && continue
    echo "  $name: HTTP $(http_code "$url")  ($url)"
done <<< "$HTTP_CHECKS"

echo; echo "## DNS (the product)"
echo "  google.com -> $(dig +short +time=3 +tries=1 @127.0.0.1 google.com 2>/dev/null | head -1)"
echo "  doubleclick.net -> $(dig +short +time=3 +tries=1 @127.0.0.1 doubleclick.net 2>/dev/null | head -1) (0.0.0.0 = blocked, good)"
echo "  pihole today:"; prom 'pihole_dns_queries_today'; prom 'pihole_ads_blocked_today'

echo; echo "## Availability probes (probe_success, 1 = up)"
prom 'probe_success'

echo; echo "## Incidents — last 24h (sentinel auto-remediation log)"
RECENT=$(find "$INCIDENT_DIR/new" "$INCIDENT_DIR/archive" -name '*.md' -mtime -1 2>/dev/null | sort)
if [ -n "$RECENT" ]; then
    while read -r f; do echo "  $(basename "$f"): $(head -1 "$f" | sed 's/# Incident: //')"; done <<< "$RECENT"
else echo "  none — nothing went down, nothing needed fixing"; fi
NEWC=$(ls "$INCIDENT_DIR/new" 2>/dev/null | wc -l)
[ "$NEWC" -gt 0 ] && echo "  >> $NEWC incident(s) awaiting agent RCA in incidents/new/"

echo; echo "## Wi-Fi health (per-device)"
WIFI_TOKEN=$(grep '^WIFI_ADMIN_PASSWORD=' "$HOME/pi-fleet/.env" 2>/dev/null | cut -d= -f2-)
curl -s -m 8 -H "X-Admin-Token: $WIFI_TOKEN" "http://localhost:3005/api/admin/devices" \
  | python3 -c "import sys,json
try:
    d=json.load(sys.stdin); devs=d.get('devices',[])
    print(f\"  {d.get('active','?')}/{d.get('count','?')} devices active on {d.get('subnet','')}\")
    for x in [v for v in devs if v.get('active')][:14]:
        name=(x.get('hostname') or x.get('ip') or '?')[:24]; room=(x.get('room') or '-')[:12]
        lc=x.get('last_check') or {}
        if lc.get('rtt_ms') is not None:
            h=f\"{lc['rtt_ms']:.0f}ms, {(lc.get('loss') or 0)*100:.0f}% loss, {lc.get('download_mbps','?')}/{lc.get('upload_mbps','?')} Mbps\"
        else: h='no check run yet'
        print(f\"  {name:24} {room:12} {h}\")
    if not devs: print('  (no devices listed — admin disabled or ARP sweep empty)')
except Exception as e: print(f'  (wifi-health admin API unavailable: {e})')"
echo "  RF — busiest channels (neighbour AP count):"
curl -s -m 8 "http://localhost:9090/api/v1/query" --data-urlencode "query=topk(4, wifi_rf_channel_ap_count)" \
  | python3 -c "import sys,json
try:
    res=json.load(sys.stdin)['data']['result']
    for r in res: m=r['metric']; print(f\"    ch {m.get('channel','?')} ({m.get('band','?')}): {r['value'][1]} APs\")
    if not res: print('    (no RF data yet)')
except Exception: print('    (rf query failed)')"
echo "  note: microwave/noise-floor detection needs a survey-capable radio (onboard Broadcom can't — ROADMAP v0.5 P2)"

echo; echo "## Sentinel"
echo "  last check: $(cat "$STATE_DIR/last-run" 2>/dev/null || echo 'never') (runs every 3 min)"
echo "  legacy jsms containers (must stay stopped): $(docker ps -a --format '{{.Names}}:{{.Status}}' | grep -E 'jsms|volhard|booth|shannon|jones' | awk -F: '{print $1"("$2")"}' | tr '\n' ' ')"
echo; echo "-- generated by fleet-report.sh on pi-node1"
)

echo "$REPORT"
if [ "${1:-}" = "email" ]; then
    # Sentinel/CTO pass: Claude writes the executive summary (incl. RCA digest of recent
    # incidents). If Claude can't run (no auth/credits), the raw report still goes out.
    export PATH=$HOME/.local/bin:$PATH
    if [ -f "$HOME/pi-fleet/secrets/claude.env" ]; then set -a; . "$HOME/pi-fleet/secrets/claude.env"; set +a
    elif [ -f "$HOME/apps/secrets/stock-backend.env" ]; then
        export "$(grep '^ANTHROPIC_API_KEY=' "$HOME/apps/secrets/stock-backend.env")"
    fi
    SUMMARY=$(echo "$REPORT" | timeout 300 claude -p "You are the CTO of this home-infra fleet \
reporting to the owner. Below is the raw twice-daily status report. Write a 5-10 line executive \
summary: overall verdict first, anything degraded/failing with cause, incidents since last \
report and how they were resolved (read any files in /home/pi/pi-fleet/incidents/new/ for \
detail), and anything needing the owner's action. Plain text, no markdown headers." \
        --model "${REPORT_MODEL:-claude-haiku-4-5-20251001}" --max-turns 8 \
        --dangerously-skip-permissions 2>/dev/null)
    SUBJECT="[pi-fleet] $VERDICT — status report $(date '+%F %H:%M')"
    [ -z "$SUMMARY" ] && SUBJECT="$SUBJECT (agent unavailable)"
    printf '%s' "$REPORT" | python3 "$(dirname "$0")/mailfmt.py" report "$VERDICT" "$SUMMARY" \
        | send_mail "$SUBJECT"
fi
