#!/usr/bin/env python3
"""mailfmt.py <mode> <status> [summary] — render a pi-fleet status report or incident
as an HTML email (stdlib only, no deps). stdin = raw report/incident text.

Modes:
  report   <VERDICT>  [SUMMARY]   VERDICT:  OK | DEGRADED
  incident <STATUS>                STATUS:  RESOLVED | MITIGATED | NEEDS-CTO | UNFIXABLE |
                                            DETECTED | SENTINEL-UNAVAILABLE

Output (stdout): a full HTML document. send-mail.py detects the <!DOCTYPE html> and sends
it as multipart/alternative with an auto-generated plain-text fallback.

Rendering rules (input is the loosely-markdown text fleet-report.sh / incidents/*.md use):
  - "# " / "## " / "### "  -> headings
  - ```fenced``` blocks and lines indented by >=2 spaces -> monospace blocks; anything
    longer than COLLAPSE_THRESHOLD lines is wrapped in a collapsible <details> (this is
    where the noisy docker-ps tables and log dumps go)
  - "- " lines -> bullets
  - "!! ..." lines -> red callout
  - bare "Status: WORD" lines -> a colored status badge
  - "**bold**", "_italic_", "`code`" -> inline styling
"""
import sys
import re
import html

sys.stdin.reconfigure(encoding="utf-8", errors="replace")
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

COLORS = {
    "OK": "#16a34a",
    "RESOLVED": "#16a34a",
    "MITIGATED": "#d97706",
    "DEGRADED": "#dc2626",
    "DETECTED": "#d97706",
    "NEEDS-CTO": "#dc2626",
    "UNFIXABLE": "#dc2626",
    "SENTINEL-UNAVAILABLE": "#dc2626",
}
DEFAULT_COLOR = "#d97706"
COLLAPSE_THRESHOLD = 6  # lines


def esc(s):
    return html.escape(s, quote=False)


def inline(s):
    s = esc(s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<!\w)_(.+?)_(?!\w)", r"<em>\1</em>", s)
    s = re.sub(r"`(.+?)`", r'<code style="background:#f4f4f5;padding:1px 4px;border-radius:4px;">\1</code>', s)
    return s


def render_block(lines):
    """A list of raw lines -> <pre>, collapsed in <details> if long."""
    while lines and not lines[0].strip():
        lines = lines[1:]
    while lines and not lines[-1].strip():
        lines = lines[:-1]
    if not lines:
        return ""
    text = esc("\n".join(lines))
    pre = (
        '<pre style="background:#f4f4f5;border-radius:6px;padding:10px 12px;'
        'overflow-x:auto;font-size:12px;line-height:1.4;margin:6px 0;'
        'white-space:pre-wrap;">' + text + "</pre>"
    )
    if len(lines) > COLLAPSE_THRESHOLD:
        return (
            f'<details style="margin:6px 0;"><summary style="cursor:pointer;'
            f'color:#6b7280;font-size:12px;">{len(lines)} lines — tap to expand</summary>{pre}</details>'
        )
    return pre


def status_badge(word):
    c = COLORS.get(word.upper(), DEFAULT_COLOR)
    return (
        f'<div style="display:inline-block;background:{c};color:#fff;border-radius:4px;'
        f'padding:2px 10px;font-weight:700;font-size:12px;margin:6px 0;">Status: {esc(word.upper())}</div>'
    )


HEADING_TAG = {1: "h2", 2: "h3", 3: "h4"}


def md_to_html(text):
    out = []
    block = []
    lines = text.splitlines()
    i, n = 0, len(lines)

    def flush():
        if block:
            out.append(render_block(block))
            block.clear()

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if stripped.startswith("```"):
            flush()
            i += 1
            fence = []
            while i < n and not lines[i].strip().startswith("```"):
                fence.append(lines[i])
                i += 1
            out.append(render_block(fence))
            i += 1
            continue

        if re.match(r"^(=+|-{3,})$", stripped):
            flush()
            i += 1
            continue

        if stripped.startswith("-- generated by"):
            i += 1
            continue

        m = re.match(r"^(#{1,3})\s+(.*)", line)
        if m:
            flush()
            tag = HEADING_TAG[len(m.group(1))]
            out.append(f'<{tag} style="margin:18px 0 6px;color:#111827;">{inline(m.group(2))}</{tag}>')
            i += 1
            continue

        if line.startswith("  ") and stripped:
            block.append(line[2:])
            i += 1
            continue

        flush()

        if not stripped:
            i += 1
            continue

        m = re.match(r"^\*{0,2}Status:\s*([A-Za-z-]+)\*{0,2}$", stripped)
        if m:
            out.append(status_badge(m.group(1)))
            i += 1
            continue

        if stripped.startswith("!!"):
            out.append(
                '<div style="background:#fef2f2;color:#991b1b;border-radius:6px;'
                f'padding:6px 10px;margin:6px 0;font-weight:600;">{inline(stripped)}</div>'
            )
            i += 1
            continue

        if stripped.startswith("- "):
            out.append(f'<div style="margin:2px 0 2px 4px;">&bull;&nbsp; {inline(stripped[2:])}</div>')
            i += 1
            continue

        out.append(f'<p style="margin:4px 0;">{inline(line)}</p>')
        i += 1

    flush()
    return "\n".join(out)


def wrap(title, color, body_html, footer):
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1f2937;">
  <div style="max-width:680px;margin:0 auto;background:#ffffff;">
    <div style="background:{color};color:#ffffff;padding:14px 20px;font-size:17px;font-weight:700;">
      {esc(title)}
    </div>
    <div style="padding:14px 20px;font-size:14px;line-height:1.5;">
{body_html}
    </div>
    <div style="padding:10px 20px;color:#9ca3af;font-size:11px;border-top:1px solid #e5e7eb;">{esc(footer)}</div>
  </div>
</body></html>
"""


def main():
    if len(sys.argv) < 3:
        sys.stderr.write("usage: mailfmt.py <report|incident> <status> [summary]\n")
        sys.exit(1)
    mode, status = sys.argv[1], sys.argv[2]
    body = sys.stdin.read()
    color = COLORS.get(status.upper(), DEFAULT_COLOR)

    if mode == "report":
        summary = sys.argv[3] if len(sys.argv) > 3 else ""
        parts = []
        if summary.strip():
            parts.append(md_to_html(summary))
        else:
            parts.append(
                '<p style="color:#9ca3af;font-style:italic;">'
                "(Claude executive summary unavailable this run — raw report below)</p>"
            )
        parts.append('<hr style="border:none;border-top:1px solid #e5e7eb;margin:14px 0;">')
        parts.append(md_to_html(body))
        sys.stdout.write(wrap(f"pi-fleet — {status}", color, "\n".join(parts), "fleet-report.sh on pi-node1"))
    elif mode == "incident":
        sys.stdout.write(wrap(f"pi-fleet incident — {status}", color, md_to_html(body), "sentinel-agent.sh on pi-node1"))
    else:
        sys.stderr.write(f"unknown mode: {mode}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
